# Generated by Django 6.0.4 on 2026-04-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RepositoryAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_url", models.URLField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("stars", models.IntegerField(default=0)),
                ("language", models.CharField(blank=True, max_length=100, null=True)),
                ("issues", models.IntegerField(default=0)),
                ("summary", models.TextField(blank=True, null=True)),
                ("rating", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
