# Generated by Django 6.0.4 on 2026-04-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositoryanalysis",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
